### ISSUE TITLE
configuring the fields in the tax cacluator

### ISSUE THREAD

**Issue by Mark-UCB** [ExLibrisGroup/alma-invoice-line-tax-calculator#14]
I'd like to know how I configure the field options in the tax calculator. Simple example, I wish to add a sales tax entry and a use tax entry and be able to apply both to a regular line type.

**Comment by jweisman** [comment]
Hi @Mark-UCB - thanks for your question. Have you seen the [help page](https://github.com/ExLibrisGroup/alma-invoice-line-tax-calculator/wiki/Help)? It explains how to set tax rates and then apply them to selected invoices. 

Let us know please if it's not clear and we help.

**Comment by Mark-UCB** [comment]
I've seen it. The screen shot of "Settings" shows more things one can set
than my installed version and I don't see anything in the instructions on
how to add value to that. Also, I see three fields "tax", "tax", "UseTax".

Also the instructions say: "enter the desired tax rate for each invoice
line type"

That leads me to confusion around how I could charge BOTH sales and use tax
to a "regular" line type, since the variables in the Settings field would
appear to be referring to line types, not multiple uses of different tax
types. For example, I want to charge 5% sales tax to the regular linetype,
and also charge 1.5% use tax.  My installation doesn't have that option and
I'm not sure the program supports it.

Mark



Mark Hemhauser
Head of Acquisitions, The Library
250 Moffitt Library, MC 6000
University of California, Berkeley
Berkeley, CA 94720-6000

510-664-4310

**Comment by jweisman** [comment]
Hi @Mark-UCB . This Cloud App sets the [VAT rate on the invoice line](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/020Acquisitions/030Invoicing/020Creating_Invoices#VAT_Calculation_.E2.80.93_Example), depending on the invoice line type. It sets the "VAT per invoice line" on the invoice:

<img width="1344" alt="Screen Shot 2021-06-22 at 6 14 10 " width=800 src="https://user-images.githubusercontent.com/80420/122857482-374b5f00-d321-11eb-9879-2db1100ea2e2.png">

And then sets the VAT on each invoice line:

<img width="1339" alt="Screen Shot 2021-06-22 at 6 13 49 " width=800 src="https://user-images.githubusercontent.com/80420/122857512-429e8a80-d321-11eb-8d56-5a2af07dc971.png">

Does that help?

**Comment by Mark-UCB** [comment]
Let me put it this way, the app does not support two VATs at different
rates to be separately applied to regular invoice line types? Which is a
somewhat common need in California where the vendor charges sales tax at
the wrong rate because every municipality has its own local "sales tax"
rates.

Mark Hemhauser
Head of Acquisitions, The Library
250 Moffitt Library, MC 6000
University of California, Berkeley
Berkeley, CA 94720-6000

510-664-4310

**Comment by jweisman** [comment]
I think perhaps the disconnect here is how your scenario is supposed to look in Alma. Can you explain/show how this would look on an invoice/line in Alma? Then we can see if the app supports it. Thanks for your patience.

**Comment by Mark-UCB** [comment]
We have an invoice line item and the vendor has charged us 8% sales tax.
The correct sales tax is 9.25%. Therefore we need to pay, on our on behalf
1.25% use tax to the state. We need to pay that on the line price, not the
line price plus sales tax. So we need the sales tax in the total price, but
not  the line price. Then we flag the line price as taxable at the 1.25%
rate and campus will pay the state 1.25% of the line price.

Mark Hemhauser
Head of Acquisitions, The Library
250 Moffitt Library, MC 6000
University of California, Berkeley
Berkeley, CA 94720-6000

510-664-4310

**Comment by jweisman** [comment]
I understand this issue is being addressed as an enhancement request in Alma invoice handling rather than a change to the Cloud App. Closing for now. Thanks.
