### ISSUE TITLE
The 'Invoice line tax calculator' cloud app does not have an 'Expand' option.   It should get one.

### ISSUE THREAD

**Issue by YoelKortick** [ExLibrisGroup/alma-invoice-line-tax-calculator#8]
The 'Alma Refine' cloud app has an 'Expand' option.  Picture below on left.
The 'Invoice line tax calculator' cloud app does not have an 'Expand' option.  Picture below center.
It would be very useful to have an expand option for the 'Invoice line tax calculator' cloud app.
It would for example make the filling in of the settings a lot more readable.  Picture below on right.

![image](https://user-images.githubusercontent.com/13975746/115242493-94ad0f00-a12a-11eb-9902-134777761645.png)

**Comment by jweisman** [comment]
Resolved in version 1.0.0
